DROP TABLE IF EXISTS App_user CASCADE;
DROP TABLE IF EXISTS Project CASCADE;
DROP TABLE IF EXISTS UserRole CASCADE;
DROP TABLE IF EXISTS App_user_roles CASCADE;
DROP TABLE IF EXISTS ChatMessage CASCADE;
DROP TABLE IF EXISTS AgreementTemplate CASCADE;


CREATE TABLE AgreementTemplate (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        content TEXT
);

CREATE TABLE App_user (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        DTYPE VARCHAR(255),
        firstName VARCHAR(255),
        lastName VARCHAR(255),
        email VARCHAR(255) UNIQUE,
        password VARCHAR(255),
        birthdate DATE,
        address VARCHAR(255),
        taxOffice VARCHAR(255),
        bankAccountNumber VARCHAR(255),
        pesel VARCHAR(11) UNIQUE,
        instrument VARCHAR(255)
);

CREATE TABLE Project (
         id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
         name VARCHAR(255) NOT NULL,
         description TEXT,
         startDate DATE,
         endDate DATE,
         status VARCHAR(50) NOT NULL,
         agreementTemplate_id BIGINT,
         CONSTRAINT fk_project_agreement_template
             FOREIGN KEY (agreementTemplate_id)
                 REFERENCES AgreementTemplate(id)
                 ON DELETE SET NULL
);

CREATE TABLE ChatMessage (
        id BIGINT AUTO_INCREMENT PRIMARY KEY,
        senderId BIGINT,
        receiverId BIGINT,
        messageContent VARCHAR(255),
        timestamp DATETIME
);

CREATE TABLE UserRole (
      id LONG AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(255),
      description VARCHAR(255)
);

CREATE TABLE App_user_roles (
      User_id LONG,
      roles_id LONG,
      FOREIGN KEY (User_id) REFERENCES App_user(id),
      FOREIGN KEY (roles_id) REFERENCES UserRole(id)
);

